apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ${apiname}
  namespace: ${namespace}
spec:
  gateways:
  - ${apiname}-gateway
  hosts:
  - '*'
  http:
  - headers:
      response:
        add:
          api-version: v${version}
    rewrite:
        uri: /api
    route:
    - destination:
        host: ${apiname}
        port:
          number: 8080
  - match:
    - uri:
        prefix: /api/${apiname}
    rewrite:
        uri: /api
    route:
    - destination:
        host: ${apiname}
        port:
          number: 8080
